export const SET_AUTHENTICATION = "SET_AUTHENTICATION";
export const INCREMENT_ACTION_COUNT = "INCREMENT_ACTION_COUNT";
export const PARSE_ERROR = "PARSE_ERROR";
export const RESET_ERROR = "RESET_ERROR";
export const GET_ALL_WISH = "GET_ALL_WISH";
export const GET_ALL_GAMES = "GET_ALL_GAMES";
export const ADD_WISHLIST = "ADD_WISHLIST";
export const REMOVE_WISHLIST = "REMOVE_WISHLIST";
