export const SET_AUTHENTICATION = "SET_AUTHENTICATION";
export const INCREMENT_ACTION_COUNT = "INCREMENT_ACTION_COUNT";
export const PARSE_ERROR = "PARSE_ERROR";
export const RESET_ERROR = "RESET_ERROR";
